version: "3"

volumes:
  postgres-data:

services:

  server:
    image: redash/redash:latest
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      # <username>:<password>@<servername>/<dbname>
      REDASH_DATABASE_URL: "postgresql://postgres:secret@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret

  worker:
    image: redash/redash:latest
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      # <username>:<password>@<servername>/<dbname>
      REDASH_DATABASE_URL: "postgresql://postgres:secret@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2

  redis:
    image: redis:2.8

  postgres:
    image: postgres:9.3
    # expose 5432 by default
    environment:
      POSTGRES_PASSWORD: secret
      # POSTGRES_USER: postgres by default
      # PGDATA: /var/lib/postgresql/data by default
      # POSTGRES_DB: $POSTGRES_USER=postgres by default
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: redash/nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - server
    links:
      - server:redash
